apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::601930231965:role/eksctl-roboshop-nodegroup-spot-NodeInstanceRole-bHrNV0DXBqUB
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - roboshop-trainee
      userarn: arn:aws:iam::601930231965:user/suresh
      username: suresh    
kind: ConfigMap
metadata:
  creationTimestamp: "2026-04-15T12:47:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1196"
  uid: 253b9a75-cd24-4eb0-8e92-e7e6aacabbe7
